"""Spawn / track / shutdown TRACE32 PowerView instances.

A TRACE32 instance is one PowerView (or simulator) process bound to an RCL
port. Each binary corresponds to one CPU family:

    t32marm     -> ARM / Cortex-M / Cortex-A simulator
    t32mppc     -> PowerPC
    t32mtricore -> Infineon TriCore
    t32mrv      -> RISC-V
    ...

This module:
  * locates the right binary in $T32SYS/bin/<host_triple>/
  * picks a free TCP port if the caller didn't pin one
  * generates a minimal config.t32 (RCL=NETASSIST, PORT, NODE)
  * launches the process with stdout/stderr → log file
  * waits for the RCL port to respond (or kills the process and reports timeout)
  * tracks every spawned process in a registry so we can list / shutdown them
  * registers atexit handlers so a crashing MCP doesn't leave orphan T32s
"""

from __future__ import annotations

import atexit
import os
import platform
import shutil
import signal
import socket
import subprocess
import tempfile
import threading
import time
from contextlib import closing
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional


# --- arch → binary map ------------------------------------------------------

ARCH_BINARIES: dict[str, str] = {
    "arm":      "t32marm",
    "cortexm":  "t32marm",
    "cortexa":  "t32marm",
    "armv8":    "t32marm64",
    "armv9":    "t32marm64",
    "tricore":  "t32mtc",
    "ppc":      "t32mppc",
    "powerpc":  "t32mppc",
    "riscv":    "t32mriscv",
    "x86":      "t32mx86",
    "x86_64":   "t32mx86_64",
    "xtensa":   "t32mxtensa",
}


def supported_arches() -> list[str]:
    return sorted(ARCH_BINARIES.keys())


def _host_triple() -> str:
    """T32 ships per-host subdirs under bin/, e.g. mac64, pc_linux64, windows64."""
    sysname = platform.system()
    arch = platform.machine().lower()
    if sysname == "Darwin":
        return "mac64"
    if sysname == "Linux":
        return "pc_linux64" if arch in ("x86_64", "amd64") else "pc_linux"
    if sysname == "Windows":
        return "windows64" if arch in ("amd64", "x86_64") else "windows"
    raise RuntimeError(f"unsupported host: {sysname} / {arch}")


def find_t32_binary(arch: str, t32sys: str | os.PathLike | None = None) -> Path:
    """Resolve the PowerView/simulator binary for a CPU family."""
    bin_name = ARCH_BINARIES.get(arch.lower())
    if bin_name is None:
        raise ValueError(f"unknown arch {arch!r}. Supported: {supported_arches()}")
    if platform.system() == "Windows":
        bin_name += ".exe"

    roots: list[Path] = []
    if t32sys:
        roots.append(Path(t32sys).expanduser())
    env = os.environ.get("T32SYS")
    if env:
        roots.append(Path(env).expanduser())
    roots.extend([
        Path("/Applications/t32"),
        Path.home() / "t32",
        Path("/opt/t32"),
        Path("/usr/local/t32"),
        Path("C:\\T32"),
    ])

    for root in roots:
        # Standard layout: <root>/bin/<host_triple>/<binary>
        candidate = root / "bin" / _host_triple() / bin_name
        if candidate.exists():
            return candidate
        # Some installs flatten to <root>/bin/<binary>
        candidate = root / "bin" / bin_name
        if candidate.exists():
            return candidate

    # Fall back to PATH lookup
    on_path = shutil.which(bin_name)
    if on_path:
        return Path(on_path)
    raise FileNotFoundError(
        f"could not find {bin_name}. Set $T32SYS to a TRACE32 installation, "
        f"or put {bin_name} on $PATH."
    )


# --- free port ---------------------------------------------------------------

def pick_free_port() -> int:
    """Bind, ask the kernel for an ephemeral port, release. The port may race
    with another process if many spawns happen at once; for typical use this
    is fine.
    """
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def is_port_open(host: str, port: int, timeout: float = 0.3) -> bool:
    """Whether something is listening on host:port (TCP)."""
    try:
        with closing(socket.create_connection((host, port), timeout=timeout)):
            return True
    except OSError:
        return False


# --- config.t32 generation ---------------------------------------------------

CONFIG_T32_TEMPLATE = """\
; auto-generated by trace32-mcp
OS=
ID=T32_{node}
TMP=/tmp

PBI=SIM

RCL=NETASSIST
PORT={port}
PACKLEN={packlen}

; Force a dedicated AREA so the MCP can scrape all command output
; (this is replayed at session-connect time via 'AREA.CREATE MCPLOG' as well)
SCREEN=
HEADER=Trace32-MCP {node}
"""


def write_config_t32(dst_dir: Path, *, port: int, node: str, packlen: int = 1024) -> Path:
    dst_dir.mkdir(parents=True, exist_ok=True)
    cfg = dst_dir / "config.t32"
    cfg.write_text(CONFIG_T32_TEMPLATE.format(port=port, node=node, packlen=packlen))
    return cfg


# --- instance dataclass + registry ------------------------------------------

@dataclass
class T32Instance:
    node_name: str
    host: str
    port: int
    arch: str
    pid: int
    binary: str
    config_path: str
    log_path: str
    work_dir: str
    spawned_by_us: bool
    started_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["uptime_seconds"] = round(time.time() - self.started_at, 1)
        d["alive"] = self.is_alive()
        return d

    def is_alive(self) -> bool:
        if not self.spawned_by_us:
            # External T32 — just probe the port
            return is_port_open(self.host, self.port, timeout=0.2)
        if self.pid <= 0:
            # Fake instance (pid==0) — never call os.kill which would target
            # the whole process group; just say "no kernel process".
            return False
        try:
            os.kill(self.pid, 0)
        except OSError:
            return False
        return True

    def tail_log(self, n: int = 80) -> str:
        try:
            with open(self.log_path, "rb") as f:
                # Read at most last 64 KB then slice last n lines
                f.seek(0, os.SEEK_END)
                size = f.tell()
                f.seek(max(0, size - 65536))
                data = f.read().decode("utf-8", errors="replace")
            lines = data.splitlines()
            return "\n".join(lines[-n:])
        except FileNotFoundError:
            return ""


class InstanceRegistry:
    """In-memory registry of TRACE32 instances we either spawned or attached to.

    Thread-safe. Cleans up spawned processes on interpreter exit.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._by_node: dict[str, T32Instance] = {}
        atexit.register(self._cleanup_atexit)

    def register(self, inst: T32Instance) -> None:
        with self._lock:
            self._by_node[inst.node_name] = inst

    def get_by_node(self, node: str) -> T32Instance | None:
        with self._lock:
            return self._by_node.get(node)

    def get_by_endpoint(self, host: str, port: int) -> T32Instance | None:
        with self._lock:
            for inst in self._by_node.values():
                if inst.host == host and inst.port == port:
                    return inst
        return None

    def remove(self, node: str) -> T32Instance | None:
        with self._lock:
            return self._by_node.pop(node, None)

    def list(self) -> list[T32Instance]:
        with self._lock:
            return list(self._by_node.values())

    def shutdown(self, node: str, force: bool = False, timeout: float = 5.0) -> dict:
        inst = self.get_by_node(node)
        if inst is None:
            return {"ok": False, "error": f"no instance named {node!r}"}

        # Best-effort RCL Quit first
        try:
            from .t32_client import T32Client, T32Endpoint
            client = T32Client(T32Endpoint(host=inst.host, port=inst.port, node_name=inst.node_name))
            try:
                client.cmd("QUIT")
            except Exception:
                pass
            finally:
                client.close()
        except Exception:
            pass

        if not inst.spawned_by_us:
            self.remove(node)
            return {"ok": True, "method": "detach_only", "instance": inst.to_dict()}

        if inst.pid <= 0:
            # Fake instance — nothing to signal
            self.remove(node)
            return {"ok": True, "method": "fake_remove", "instance": inst.to_dict()}

        # Process management — portable terminate/kill
        _terminate(inst.pid)

        deadline = time.time() + timeout
        while time.time() < deadline:
            if not inst.is_alive():
                break
            time.sleep(0.1)

        if inst.is_alive() and force:
            _kill(inst.pid)

        self.remove(node)
        return {"ok": True, "method": "signal", "instance": inst.to_dict()}

    def _cleanup_atexit(self) -> None:
        for inst in self.list():
            if not inst.spawned_by_us:
                continue
            if inst.pid <= 0:
                # Fake / sentinel — nothing to signal
                continue
            if inst.is_alive():
                _terminate(inst.pid)


_REGISTRY = InstanceRegistry()


def registry() -> InstanceRegistry:
    return _REGISTRY


# --- spawn -------------------------------------------------------------------

class SpawnTimeout(RuntimeError):
    pass


def _terminate(pid: int) -> None:
    """Portable graceful terminate. SIGTERM on POSIX, CTRL_BREAK_EVENT on Windows."""
    if pid <= 0:
        return
    try:
        if platform.system() == "Windows":
            # Send CTRL_BREAK_EVENT to the process group we created via CREATE_NEW_PROCESS_GROUP.
            os.kill(pid, signal.CTRL_BREAK_EVENT)  # type: ignore[attr-defined]
        else:
            os.kill(pid, signal.SIGTERM)
    except (ProcessLookupError, OSError):
        pass


def _kill(pid: int) -> None:
    """Portable hard kill. SIGKILL on POSIX, TerminateProcess via SIGTERM on Windows."""
    if pid <= 0:
        return
    try:
        if platform.system() == "Windows":
            # On Windows, signal.SIGTERM under os.kill calls TerminateProcess
            os.kill(pid, signal.SIGTERM)
        else:
            os.kill(pid, signal.SIGKILL)
    except (ProcessLookupError, OSError):
        pass


def spawn(
    arch: str,
    *,
    port: int | None = None,
    node_name: str | None = None,
    t32sys: str | None = None,
    headless: bool = False,
    extra_args: list[str] | None = None,
    timeout_seconds: float = 20.0,
) -> T32Instance:
    """Launch a TRACE32 PowerView/simulator process and wait for its RCL port.

    Raises SpawnTimeout if the process is up but the port never responds.
    In fake mode (T32_MCP_FAKE=1) returns a registered fake instance without
    launching anything.
    """
    from .t32_fake import is_fake_mode, make_fake_instance

    if is_fake_mode():
        inst = make_fake_instance(arch, port, node_name)
        _REGISTRY.register(inst)
        return inst

    binary = find_t32_binary(arch, t32sys=t32sys)
    chosen_port = port if port is not None else pick_free_port()
    node = node_name or f"T32_{arch.upper()}_{chosen_port}"

    work_dir = Path(tempfile.mkdtemp(prefix=f"trace32_mcp_{node}_"))
    config_path = write_config_t32(work_dir, port=chosen_port, node=node)
    log_path = work_dir / "t32.log"

    argv: list[str] = [str(binary), "-c", str(config_path)]
    if headless and platform.system() != "Windows":
        # T32 does not have a true headless mode, but we can hint at it on Linux
        argv += ["-nofbsync"]
    if extra_args:
        argv += extra_args

    env = os.environ.copy()
    env.setdefault("T32SYS", str(binary.parent.parent.parent))  # bin/<triple>/<bin> -> root

    log_fh = open(log_path, "wb")
    popen_kwargs: dict = {
        "cwd": str(work_dir),
        "env": env,
        "stdout": log_fh,
        "stderr": subprocess.STDOUT,
    }
    if platform.system() == "Windows":
        # CREATE_NEW_PROCESS_GROUP lets us send CTRL_BREAK_EVENT to just this group
        popen_kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
    else:
        popen_kwargs["start_new_session"] = True  # POSIX: detach from our session
    proc = subprocess.Popen(argv, **popen_kwargs)

    # Wait for the RCL port
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if proc.poll() is not None:
            log_fh.close()
            raise RuntimeError(
                f"TRACE32 binary exited early (rc={proc.returncode}). "
                f"Log tail:\n{Path(log_path).read_text(errors='replace')[-2000:]}"
            )
        if is_port_open("127.0.0.1", chosen_port, timeout=0.3):
            break
        time.sleep(0.2)
    else:
        _terminate(proc.pid)
        log_fh.close()
        raise SpawnTimeout(
            f"TRACE32 spawned (pid={proc.pid}) but port {chosen_port} never opened "
            f"within {timeout_seconds}s. Log tail:\n"
            f"{Path(log_path).read_text(errors='replace')[-2000:]}"
        )

    log_fh.close()

    inst = T32Instance(
        node_name=node,
        host="127.0.0.1",
        port=chosen_port,
        arch=arch,
        pid=proc.pid,
        binary=str(binary),
        config_path=str(config_path),
        log_path=str(log_path),
        work_dir=str(work_dir),
        spawned_by_us=True,
    )
    _REGISTRY.register(inst)
    return inst


def attach(
    host: str,
    port: int,
    *,
    node_name: str | None = None,
    arch: str = "unknown",
) -> T32Instance:
    """Register an externally-started TRACE32 in our registry.

    No process management responsibility (spawned_by_us=False) — shutdown will
    only QUIT it over RCL, not SIGTERM.
    """
    from .t32_fake import is_fake_mode
    if is_fake_mode():
        node = node_name or f"FAKE_external_{host}_{port}"
        existing = _REGISTRY.get_by_endpoint(host, port)
        if existing:
            return existing
        inst = T32Instance(
            node_name=node, host=host, port=port, arch=arch,
            pid=0, binary="(fake-external)", config_path="", log_path="", work_dir="",
            spawned_by_us=False,
        )
        _REGISTRY.register(inst)
        return inst

    if not is_port_open(host, port, timeout=0.5):
        raise ConnectionError(f"nothing listening on {host}:{port}")
    node = node_name or f"T32_external_{host}_{port}"
    existing = _REGISTRY.get_by_endpoint(host, port)
    if existing:
        return existing
    inst = T32Instance(
        node_name=node,
        host=host,
        port=port,
        arch=arch,
        pid=0,
        binary="(external)",
        config_path="",
        log_path="",
        work_dir="",
        spawned_by_us=False,
    )
    _REGISTRY.register(inst)
    return inst


def connect_or_spawn(
    arch: str = "arm",
    *,
    host: str = "127.0.0.1",
    port: int | None = None,
    node_name: str | None = None,
    t32sys: str | None = None,
    headless: bool = False,
) -> T32Instance:
    """If something already listens on host:port, attach to it.
    Otherwise spawn a new instance (on the requested port, or an ephemeral free one).
    """
    if port is not None and is_port_open(host, port):
        return attach(host, port, node_name=node_name, arch=arch)
    return spawn(
        arch,
        port=port,
        node_name=node_name,
        t32sys=t32sys,
        headless=headless,
    )
